import {
  useEffect,
  useState,
} from 'react';

import Head from 'next/head';

import CSVReader from '../components/CSVReader';
import NestedTable from '../components/NestedTable';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [results, setResults] = useState([]);

  useEffect(() => {
    console.log({ results });
  }, [results]);

  const handleCsvResults = (csvData) => {
    const lookup = {};
    csvData.forEach(
      ({
        Source_Vendor,
        Invoice_Id,
        Invoice_Date,
        Due_Date,
        Customer_Id,
        Invoice_Amount,
        Item_Id,
        Item_code,
        Title,
        Quantity,
        Unit_Price,
        Tax,
        Amount,
      }) => {
        if (Invoice_Id && !lookup[Invoice_Id]) {
          lookup[Invoice_Id] = {
            Source_Vendor,
            Invoice_Id,
            Invoice_Date,
            Due_Date,
            Customer_Id,
            Invoice_Amount,
            nested: [],
          };
          // on first turn, add elements
          lookup[Invoice_Id].nested.push({
            Item_Id,
            Item_code,
            Title,
            Quantity,
            Unit_Price,
            Tax,
            Amount,
          });
        } else if (Invoice_Id && lookup[Invoice_Id]) {
          lookup[Invoice_Id].nested.push({
            Item_Id,
            Item_code,
            Title,
            Quantity,
            Unit_Price,
            Tax,
            Amount,
          });
        } else {
          console.log("Something went wrong", lookup);
        }
      }
    );
    console.log("final results", lookup);
    const filteredArr = Object.values(lookup).map((d) => d);
    setResults(filteredArr);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}
        <CSVReader handleCsvResults={handleCsvResults} />
        <div className="separator"></div>
        <NestedTable data={results} />
      </main>

      <footer className={styles.footer}>
        <a href="https://nisum.com" target="_blank" rel="noopener noreferrer">
          Powered by Nisum
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  );
}
